#!/usr/bin/env bash
# Bash script that installs Nginx, updates index file and restarts Nginx

# Install Nginx
apt-get update
apt-get -y install nginx

# Allow incoming HTTP traffic through UFW
ufw allow 'Nginx HTTP'

# Updating index file
echo 'Hello World!' > /var/www/html/index.html

# Restart Nginx
service nginx restart
