#!/usr/bin/env bash
# Bash script that cofigures Nginx so that
# /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www/html && sudo chmod -R 755 /var/www
echo "Hello World" | sudo tee /var/www/html/index.html >/dev/null
sudo sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
