#!/usr/bin/env bash
# Bash script that Installs, configures and start Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
sudo ufw allow 'Nginx HTTP'

# Override the default index file served as home page
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

#Give the user  ownership to website files
sudo chown -R $USER:$USER /var/www/html && sudo chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
sudo sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Reload Nginx
sudo service nginx start
