#!/usr/bin/env bash
# Bash script that cofigures Nginx so that
# /redirect_me is redirecting to another page

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Modify the default index file served as home page
echo 'Hello World' > /var/www/html/index.html

# Give the user permisions on the website files
sudo chown -R "$USER":"$USER" /var/www/html && sudo chmod -R 755 /var/www

# Redirect /redirect_me to a YouTube video
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Reload Nginx
sudo service nginx start
