#!/usr/bin/env bash
# Update the system
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
echo "
frontend web_servers
    bind *:80
    mode http
    default_backend servers

backend servers
    balance roundrobin
    server 209086-web-01 52.73.28.65:80
    server 209086-web-02 54.90.18.103:80
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy init script
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy start

