#!/usr/bin/env bash
# Script to automate to fix the server not listening on port 80

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
