#!/usr/bin/env bash
# Bash script that does certain operations

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 1
done
