#!/usr/bin/env bash
# Bash script that does certain operations

function quit_handler() {
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && quit_handler' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'quit_handler' SIGQUIT
done
