#!/usr/bin/env bash
# Display at 4 bad luck at 8 good luck and others Best School

count=1
while [ $count -lt 11 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
