#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and: given texts at 4, 9 and 17

count=1
while [ $count -lt 21 ]
do
	case $count in
		4)
			echo $count
			echo "bad luck from China"
			;;
		9)
			echo $count
			echo "bad luck from Japan"
			;;
		17)
			echo $count
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
	count=$((count+1))
done
