#!/bin/bash

# Block all incoming traffic by default
sudo utf default deny incoming

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
sudo ufw enable
