#!/usr/bin/env bash
# Configure your SSH configuration file to connect without typing a password

CONFIG_FILE=~/.ssh/config
PRIVATE_KEY=~/.ssh/school

if [ ! -f "$CONFIG_FILE" ]; then
	touch "$CONFIG_FILE":
fi

echo "Host 8.8.8.8" >> "$CONFIG_FILE"
echo "	IdentifyFile $PRIVATE_KEY" >> "$CONFIG_FILE"
echo "	PasswordAuthentication no" >> "$CONFIG_FILE"
